server:
  port: ${PORT}

spring:
  data:
    mongodb:
      host: ${HOST}
      port: 27017
      database: ${DATABASE}

jwt:
  secret: ${SECRET}
  access_time: ${ACCESS_TIME}
  refresh_time: ${REFRESH_TIME}