server:
  port: ${PORT}

spring:
  mail:
      host: smtp.gmail.com
      port: 587
      username: ${SMTP_USER}
      password: ${SMTP_PASS}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  data:
    mongodb:
      host: ${HOST}
      port: 27017
      database: ${DATABASE}


jwt:
  secret: ${SECRET}
  access_time: ${ACCESS_TIME}
  refresh_time: ${REFRESH_TIME}

file:
  upload_dir: "uploads/"